/**
 * Shared terminology dictionary: Persian/English equivalents for job-hunting
 * vocabulary (titles, skills, locations, employment types, remote policies,
 * seniority, industries).
 *
 * The dictionary is data, not code: it can be replaced/extended at runtime
 * (e.g. loaded from a config file) instead of being hardcoded at call sites.
 *
 * Canonical values use snake_case English; Persian forms include both ZWNJ
 * and plain-space variants (normalization collapses them anyway, but both
 * are listed for readability).
 */

export interface TerminologyEntry {
  /** Canonical English key used internally. */
  canonical: string;
  /** All surface forms (English + Persian) recognized as this term. */
  forms: string[];
  category: TerminologyCategory;
}

export type TerminologyCategory =
  'title' | 'skill' | 'location' | 'employment_type' | 'remote_policy' | 'seniority' | 'industry';

export const DEFAULT_TERMINOLOGY: TerminologyEntry[] = [
  // ---- Titles -------------------------------------------------------------
  {
    canonical: 'backend_developer',
    forms: [
      'backend developer',
      'back-end developer',
      'backend engineer',
      'back-end engineer',
      'برنامه نویس بک اند',
      'برنامه‌نویس بک‌اند',
      'توسعه دهنده بک اند',
      'توسعه‌دهنده بک‌اند',
      'برنامه نویس سمت سرور',
      'کارشناس back-end',
      'کارشناس بک اند',
      'back-end',
      'backend',
      'بک اند',
      'بک‌اند',
    ],
    category: 'title',
  },
  {
    canonical: 'frontend_developer',
    forms: [
      'frontend developer',
      'front-end developer',
      'frontend engineer',
      'front-end engineer',
      'برنامه نویس فرانت اند',
      'برنامه‌نویس فرانت‌اند',
      'توسعه دهنده فرانت اند',
      'توسعه‌دهنده فرانت اند',
      'توسعه دهنده front end',
    ],
    category: 'title',
  },
  {
    canonical: 'fullstack_developer',
    forms: [
      'fullstack developer',
      'full stack developer',
      'full-stack developer',
      'full stack engineer',
      'full-stack engineer',
      'full-stack product engineer',
      'فول استک',
      'فول‌استک',
      'برنامه نویس فول استک',
      'برنامه‌ نویس فول‌ استک',
      'مهندس full-stack',
      'کدنویس full stack',
    ],
    category: 'title',
  },
  {
    canonical: 'software_engineer',
    forms: [
      'software engineer',
      'software developer',
      'مهندس نرم افزار',
      'مهندس نرم‌افزار',
      'برنامه نویس',
      'برنامه‌نویس',
      'توسعه دهنده نرم افزار',
      'توسعه‌دهنده نرم‌افزار',
      'کارشناس توسعه نرم افزار',
      'کارشناس توسعه نرم‌افزار',
      'مهندس ارشد توسعه نرم افزار',
    ],
    category: 'title',
  },
  {
    canonical: 'web_developer',
    forms: [
      'web developer',
      'web master',
      'توسعه دهنده وب',
      'توسعه‌دهنده وب',
      'برنامه نویس وب',
      'برنامه‌نویس وب',
      'کارشناس توسعه وب',
      'کارشناس اجرایی و توسعه وب',
    ],
    category: 'title',
  },
  {
    canonical: 'devops_engineer',
    forms: [
      'devops engineer',
      'devops',
      'site reliability engineer',
      'sre',
      'platform engineer',
      'دواپس',
      'مهندس دواپس',
      'کارشناس devops',
      'کارشناس دواپس',
      'مهندس قابلیت اطمینان',
    ],
    category: 'title',
  },
  {
    canonical: 'cloud_engineer',
    forms: [
      'cloud engineer',
      'cloud architect',
      'cloud specialist',
      'مهندس ابری',
      'مهندس کامپیوتر ابری',
      'متخصص ابر',
      'کارشناس زیرساخت ابری',
    ],
    category: 'title',
  },
  {
    canonical: 'data_engineer',
    forms: ['data engineer', 'مهندس داده', 'توسعه دهنده داده'],
    category: 'title',
  },
  {
    canonical: 'data_scientist',
    forms: ['data scientist', 'دانشمند داده', 'علم داده', 'متخصص علم داده', 'کارشناس ارشد داده'],
    category: 'title',
  },
  {
    canonical: 'data_analyst',
    forms: [
      'data analyst',
      'business intelligence analyst',
      'bi analyst',
      'تحلیلگر داده',
      'کارشناس تحلیل داده',
      'هوش تجاری',
      'کارشناس هوش تجاری',
      'تحلیلگر هوشمندسازی کسب و کار',
    ],
    category: 'title',
  },
  {
    canonical: 'machine_learning_engineer',
    forms: [
      'machine learning engineer',
      'ml engineer',
      'مهندس یادگیری ماشین',
      'مهندس هوش مصنوعی',
      'متخصص هوش مصنوعی',
      'کارشناس هوش مصنوعی',
      'ai developer',
      'ai engineer',
      'توسعه دهنده هوش مصنوعی',
    ],
    category: 'title',
  },
  {
    canonical: 'ai_prompt_engineer',
    forms: [
      'vibe coder',
      'vibe coding',
      'ai vibe coder',
      'prompt engineer',
      'وایب کدینگ',
      'وایب‌کدینگ',
      'متخصص وایب کدینگ',
      'مهندس پرامپت',
    ],
    category: 'title',
  },
  {
    canonical: 'qa_engineer',
    forms: [
      'qa engineer',
      'quality assurance engineer',
      'quality assurance',
      'software tester',
      'test engineer',
      'تستر',
      'مهندس تست',
      'تضمین کیفیت',
      'کارشناس تضمین کیفیت',
      'متخصص کنترل کیفیت نرم افزار',
    ],
    category: 'title',
  },
  {
    canonical: 'scrum_master',
    forms: [
      'scrum master',
      'agile coach',
      'agile delivery manager',
      'اسکرام مستر',
      'اسکرام‌مستر',
      'مربی اجایل',
      'کارشناس اجایل',
      'متخصص متدولوژی چابک',
    ],
    category: 'title',
  },
  {
    canonical: 'product_manager',
    forms: ['product manager', 'product owner', 'مدیر محصول', 'مالک محصول', 'مدیر محصول فنی'],
    category: 'title',
  },
  {
    canonical: 'project_manager',
    forms: [
      'project manager',
      'مدیر پروژه',
      'pmo',
      'کارشناس pmo',
      'کارشناس پروژه',
      'متخصص مدیریت پروژه نرم افزاری',
    ],
    category: 'title',
  },
  {
    canonical: 'ui_ux_designer',
    forms: [
      'ui designer',
      'ux designer',
      'ui/ux designer',
      'product designer',
      'طراح رابط کاربری',
      'طراح تجربه کاربری',
      'طراح محصول',
      'طراح ui/ux',
    ],
    category: 'title',
  },
  {
    canonical: 'graphic_designer',
    forms: [
      'graphic designer',
      'graphic artist',
      'طراح گرافیک',
      'کارشناس گرافیک',
      'طراح وب سایت گرافیکی',
    ],
    category: 'title',
  },
  {
    canonical: 'mobile_developer',
    forms: [
      'mobile developer',
      'android developer',
      'ios developer',
      'flutter developer',
      'react native developer',
      'برنامه نویس موبایل',
      'برنامه‌نویس موبایل',
      'توسعه دهنده موبایل',
      'توسعه‌دهنده موبایل',
    ],
    category: 'title',
  },
  {
    canonical: 'game_developer',
    forms: [
      'game developer',
      'game programmer',
      'توسعه دهنده بازی',
      'توسعه‌دهنده بک‌اند بازی',
      'برنامه نویس بازی',
      'طراح بازی',
    ],
    category: 'title',
  },
  {
    canonical: 'network_engineer',
    forms: [
      'network engineer',
      'network administrator',
      'network expert',
      'network infrastructure',
      'مهندس شبکه',
      'مدیر شبکه',
      'کارشناس شبکه',
      'متخصص شبکه',
      'کارشناس زیرساخت شبکه',
      'noc expert',
      'کارشناس noc',
    ],
    category: 'title',
  },
  {
    canonical: 'security_engineer',
    forms: [
      'security engineer',
      'security expert',
      'security specialist',
      'امنیت',
      'مهندس امنیت',
      'امنیت سایبری',
      'کارشناس امنیت',
      'کارشناس امنیت شبکه',
      'کارشناس امنیت سایبری',
      'متخصص امنیت اطلاعات',
    ],
    category: 'title',
  },
  {
    canonical: 'database_administrator',
    forms: [
      'database administrator',
      'dba',
      'مدیر پایگاه داده',
      'مهندس پایگاه داده',
      'کارشناس پایگاه داده',
      'کارشناس ارشد پایگاه داده',
    ],
    category: 'title',
  },
  {
    canonical: 'system_administrator',
    forms: [
      'system administrator',
      'sysadmin',
      'مدیر سیستم',
      'راهبر سامانه',
      'کارشناس سیستم',
      'کارشناس فنی سیستم',
    ],
    category: 'title',
  },
  {
    canonical: 'it_support',
    forms: [
      'it support',
      'it help desk',
      'it helpdesk',
      'it service desk',
      'help desk',
      'helpdesk',
      'it specialist',
      'it expert',
      'it engineer',
      'پشتیبانی فنی',
      'کارشناس پشتیبانی فنی',
      'کارشناس فنی',
      'کارشناس IT',
      'متخصص پشتیبانی',
      'کارشناس خدمات IT',
      'کارشناس پشتیبانی و خدمات فنی',
      'فناوری اطلاعات',
    ],
    category: 'title',
  },
  {
    canonical: 'seo_specialist',
    forms: [
      'seo specialist',
      'seo expert',
      'seo',
      'کارشناس سئو',
      'کارشناس ارشد سئو',
      'کارشناس سئو و تولید محتوا',
    ],
    category: 'title',
  },
  {
    canonical: 'java_developer',
    forms: ['java developer', 'java engineer', 'برنامه نویس جاوا', 'توسعه دهنده جاوا'],
    category: 'title',
  },
  {
    canonical: 'dotnet_developer',
    forms: [
      '.net developer',
      'dotnet developer',
      'c# developer',
      'برنامه نویس دات نت',
      'برنامه‌نویس ارشد دات نت',
      'برنامه نویس سی شارپ',
      'توسعه دهنده دات نت',
    ],
    category: 'title',
  },
  {
    canonical: 'oracle_developer',
    forms: ['oracle developer', 'برنامه نویس اوراکل', 'توسعه دهنده اوراکل', 'کارشناس اوراکل'],
    category: 'title',
  },
  {
    canonical: 'erp_specialist',
    forms: [
      'erp specialist',
      'erp manager',
      'erp system manager',
      'erp analyst',
      'erp support',
      'erp functional support',
      'erp technical support',
      'کارشناس erp',
      'کارشناس ارشد erp',
      'کارشناس فنی erp',
      'کارشناس پشتیبانی فنی erp',
      'مدیر سیستم های erp',
      'کارشناس فرآیند erp',
    ],
    category: 'title',
  },
  {
    canonical: 'bi_specialist',
    forms: [
      'business intelligence',
      'business intelligence specialist',
      'bi specialist',
      'کارشناس bi',
      'متخصص هوش تجاری',
    ],
    category: 'title',
  },
  {
    canonical: 'technical_lead',
    forms: [
      'tech lead',
      'technical lead',
      'team lead',
      'lead developer',
      'chapter lead',
      'frontend chapter lead',
      'تیم لید',
      'تکنیکال لید',
      'سرپرست فنی',
      'مدیر تیم فنی',
      'رهبر تیم',
    ],
    category: 'title',
  },
  {
    canonical: 'engineering_manager',
    forms: [
      'engineering manager',
      'head of software',
      'software development manager',
      'مدیر مهندسی',
      'مدیر توسعه نرم افزار',
      'مدیر نرم افزار',
      'سرپرست توسعه نرم افزار',
    ],
    category: 'title',
  },
  {
    canonical: 'cto',
    forms: [
      'cto',
      'chief technology officer',
      'مدیر فناوری اطلاعات ارشد',
      'مدیرعامل فناوری',
      'مدیر ارشد فناوری',
    ],
    category: 'title',
  },
  {
    canonical: 'it_director',
    forms: [
      'it director',
      'director of information technology',
      'director of it',
      'مدیر فناوری اطلاعات',
      'مدیر ارشد فناوری اطلاعات',
    ],
    category: 'title',
  },
  {
    canonical: 'bioinformatics',
    forms: [
      'bioinformatics',
      'bioinformatics specialist',
      'بیوانفورماتیک',
      'کارشناس بیوانفورماتیک',
      'زیست انفورماتیک',
    ],
    category: 'title',
  },
  {
    canonical: 'electrical_engineer',
    forms: ['electrical engineer', 'مهندس برق', 'کارشناس برق', 'مهندس تاسیسات برقی'],
    category: 'title',
  },
  {
    canonical: 'automation_engineer',
    forms: [
      'automation engineer',
      'industrial control and automation',
      'مهندس اتوماسیون',
      'کارشناس کنترل و اتوماسیون صنعتی',
      'متخصص اتوماسیون صنعتی',
    ],
    category: 'title',
  },
  {
    canonical: 'hr_specialist',
    forms: [
      'hr specialist',
      'hr data analyst',
      'human resources',
      'کارشناس منابع انسانی',
      'کارشناس ارشد منابع انسانی',
      'کارشناس داده منابع انسانی',
    ],
    category: 'title',
  },
  {
    canonical: 'e_commerce_specialist',
    forms: [
      'e-commerce expert',
      'e-commerce specialist',
      'کارشناس فروشگاه اینترنتی',
      'کارشناس تجارت الکترونیک',
      'کارشناس ارشد فروشگاه آنلاین',
    ],
    category: 'title',
  },
  {
    canonical: 'jira_admin',
    forms: ['jira admin', 'jira administrator', 'کارشناس jira', 'مدیر jira'],
    category: 'title',
  },
  {
    canonical: 'sap_admin',
    forms: ['sap admin', 'sap administrator', 'کارشناس sap', 'مدیر sap'],
    category: 'title',
  },
  {
    canonical: 'sales_specialist',
    forms: [
      'sales supervisor',
      'sales specialist',
      'کارشناس فروش',
      'سرپرست فروش',
      'کارشناس ارشد فروش',
    ],
    category: 'title',
  },
  {
    canonical: 'intern',
    forms: ['internship', 'trainee', 'کارآموز', 'کارآموز فنی', 'کارآموز خدمات'],
    category: 'title',
  },

  // ---- Skills -------------------------------------------------------------
  {
    canonical: 'node.js',
    forms: ['node.js', 'nodejs', 'node js', 'node', 'نود جی اس', 'نود جی‌اس'],
    category: 'skill',
  },
  {
    canonical: 'typescript',
    forms: ['typescript', 'ts', 'تایپ‌اسکریپت', 'تایپ اسکریپت'],
    category: 'skill',
  },
  {
    canonical: 'javascript',
    forms: ['javascript', 'js', 'جاوااسکریپت', 'جاوا اسکریپت'],
    category: 'skill',
  },
  { canonical: 'python', forms: ['python', 'پایتون'], category: 'skill' },
  { canonical: 'java', forms: ['java', 'جاوا'], category: 'skill' },
  { canonical: 'c#', forms: ['c#', 'csharp', 'c sharp', 'سی شارپ'], category: 'skill' },
  { canonical: 'c++', forms: ['c++', 'cpp', 'سی پلاس پلاس'], category: 'skill' },
  { canonical: 'php', forms: ['php', 'پی اچ پی'], category: 'skill' },
  { canonical: 'golang', forms: ['golang', 'go', 'گولنگ'], category: 'skill' },
  { canonical: 'rust', forms: ['rust', 'راست'], category: 'skill' },
  {
    canonical: 'react',
    forms: ['react', 'react.js', 'reactjs', 'ری اکت', 'ری‌اکت'],
    category: 'skill',
  },
  { canonical: 'vue', forms: ['vue', 'vue.js', 'vuejs', 'ویو'], category: 'skill' },
  { canonical: 'angular', forms: ['angular', 'انگولار'], category: 'skill' },
  {
    canonical: 'next.js',
    forms: ['next.js', 'nextjs', 'next js', 'next', 'نکست'],
    category: 'skill',
  },
  { canonical: 'nuxt', forms: ['nuxt', 'nuxtjs', 'nuxt.js'], category: 'skill' },
  {
    canonical: 'postgresql',
    forms: ['postgresql', 'postgres', 'psql', 'پستگرس', 'پست گرس'],
    category: 'skill',
  },
  {
    canonical: 'mysql',
    forms: ['mysql', 'maria', 'mariadb', 'مای اس کیو ال', 'مای‌اس‌کیو‌ال'],
    category: 'skill',
  },
  {
    canonical: 'sqlserver',
    forms: ['sql server', 'microsoft sql server', 'اس کیو ال سرور'],
    category: 'skill',
  },
  {
    canonical: 'mongodb',
    forms: ['mongodb', 'mongo', 'مونگو', 'مونگو دی بی'],
    category: 'skill',
  },
  { canonical: 'redis', forms: ['redis', 'ردیس'], category: 'skill' },
  { canonical: 'kafka', forms: ['kafka', 'کافکا'], category: 'skill' },
  { canonical: 'rabbitmq', forms: ['rabbitmq', 'rabbit mq', 'ربیت ام کیو'], category: 'skill' },
  {
    canonical: 'elasticsearch',
    forms: ['elasticsearch', 'elastic', 'ایلاستیک سرچ'],
    category: 'skill',
  },
  {
    canonical: 'oracle_db',
    forms: ['oracle', 'oracle db', 'اوراکل'],
    category: 'skill',
  },
  { canonical: 'sqlite', forms: ['sqlite', 'sql lite'], category: 'skill' },
  {
    canonical: 'graphql',
    forms: ['graphql', 'graph ql', 'گراف کیو ال'],
    category: 'skill',
  },
  {
    canonical: 'microservices',
    forms: [
      'microservices',
      'microservice',
      'micro-services',
      'میکروسرویس',
      'میکرو سرویس',
      'معماری میکروسرویس',
    ],
    category: 'skill',
  },
  {
    canonical: 'docker',
    forms: ['docker', 'داکر', 'کانتینر', 'container', 'containerization'],
    category: 'skill',
  },
  {
    canonical: 'kubernetes',
    forms: ['kubernetes', 'k8s', 'کوبرنتیز', 'کوبرنتیز k8s'],
    category: 'skill',
  },
  {
    canonical: 'aws',
    forms: ['aws', 'amazon web services', 'ای دبلیو اس', 'سرویس ابری آمازون'],
    category: 'skill',
  },
  {
    canonical: 'azure',
    forms: ['azure', 'مایکروسافت آژور', 'microsoft azure'],
    category: 'skill',
  },
  {
    canonical: 'gcp',
    forms: ['gcp', 'google cloud', 'google cloud platform', 'ابر گوگل'],
    category: 'skill',
  },
  {
    canonical: 'linux',
    forms: ['linux', 'لینوکس', 'ubuntu', 'debian', 'centos', 'redhat'],
    category: 'skill',
  },
  {
    canonical: 'git',
    forms: ['git', 'گیت', 'github', 'gitlab', 'bitbucket', 'گیت هاب', 'گیت‌هاب'],
    category: 'skill',
  },
  {
    canonical: 'ci/cd',
    forms: [
      'ci/cd',
      'cicd',
      'ci cd',
      'continuous integration',
      'continuous delivery',
      'سی آی سی دی',
      'استقرار پیوسته',
    ],
    category: 'skill',
  },
  {
    canonical: 'rest_api',
    forms: ['rest api', 'restful', 'rest', 'api', 'web api', 'وب سرویس', 'restful api'],
    category: 'skill',
  },
  {
    canonical: 'html',
    forms: ['html', 'html5', 'اچ تی ام ال'],
    category: 'skill',
  },
  { canonical: 'css', forms: ['css', 'css3', 'سی اس اس'], category: 'skill' },
  {
    canonical: 'tailwind',
    forms: ['tailwind', 'tailwindcss', 'tailwind css', 'تیلویند'],
    category: 'skill',
  },
  { canonical: 'sass', forms: ['sass', 'scss', 'less'], category: 'skill' },
  { canonical: 'bootstrap', forms: ['bootstrap', 'بوتسترپ'], category: 'skill' },
  {
    canonical: 'testing',
    forms: [
      'jest',
      'vitest',
      'mocha',
      'jasmine',
      'cypress',
      'playwright',
      'selenium',
      'unit test',
      'tdd',
      'کارآزمایی واحد',
    ],
    category: 'skill',
  },
  { canonical: 'webpack', forms: ['webpack', 'vite', 'rollup', 'ویت'], category: 'skill' },
  { canonical: 'figma', forms: ['figma', 'فیگما'], category: 'skill' },
  {
    canonical: 'photoshop',
    forms: ['photoshop', 'illustrator', 'فتوشاپ', 'ایلستریتور'],
    category: 'skill',
  },
  { canonical: 'django', forms: ['django', 'جنگو'], category: 'skill' },
  { canonical: 'flask', forms: ['flask', 'فلاسک'], category: 'skill' },
  { canonical: 'laravel', forms: ['laravel', 'لاراول'], category: 'skill' },
  {
    canonical: 'spring',
    forms: ['spring', 'spring boot', 'اسپرینگ'],
    category: 'skill',
  },
  {
    canonical: 'asp.net',
    forms: ['asp.net', 'asp net', 'asp.net core', 'ای اس پی دات نت'],
    category: 'skill',
  },
  {
    canonical: '.net',
    forms: ['.net', 'dotnet', 'دات نت', '.net core'],
    category: 'skill',
  },
  { canonical: 'unity', forms: ['unity', 'یونیتی', 'unreal', 'آنریل'], category: 'skill' },
  { canonical: 'flutter', forms: ['flutter', 'فلاتر'], category: 'skill' },
  {
    canonical: 'nestjs',
    forms: ['nestjs', 'nest.js', 'nest js', 'نست'],
    category: 'skill',
  },
  {
    canonical: 'express',
    forms: ['express', 'expressjs', 'express.js', 'اکسپرس'],
    category: 'skill',
  },
  {
    canonical: 'websocket',
    forms: ['socket.io', 'websocket', 'websockets', 'سوکت', 'real-time', 'بلادرنگ'],
    category: 'skill',
  },
  {
    canonical: 'nginx',
    forms: ['nginx', 'انجینکس', 'انجین ایکس', 'reverse proxy', 'پروکسی معکوس'],
    category: 'skill',
  },
  { canonical: 'terraform', forms: ['terraform', 'ترافورم'], category: 'skill' },
  { canonical: 'ansible', forms: ['ansible', 'انسیبل'], category: 'skill' },
  {
    canonical: 'prometheus',
    forms: [
      'prometheus',
      'grafana',
      'zabbix',
      'nagios',
      'پرومتئوس',
      'گرافانا',
      'مانیتورینگ',
      'monitoring',
    ],
    category: 'skill',
  },
  {
    canonical: 'ai_llm',
    forms: [
      'artificial intelligence',
      'ai',
      'machine learning',
      'deep learning',
      'llm',
      'chatgpt',
      'openai',
      'هوش مصنوعی',
      'یادگیری ماشین',
      'یادگیری عمیق',
      'پردازش زبان طبیعی',
      'nlp',
      'computer vision',
      'بینایی ماشین',
      'vibe coding',
      'vibe coder',
      'وایب کدینگ',
      'وایب کد',
    ],
    category: 'skill',
  },
  {
    canonical: 'agile',
    forms: ['agile', 'scrum', 'kanban', 'اجایل', 'اسکرام', 'کانبان', 'متدولوژی چابک'],
    category: 'skill',
  },
  {
    canonical: 'seo',
    forms: ['seo', 'search engine optimization', 'سئو'],
    category: 'skill',
  },
  {
    canonical: 'data_analytics',
    forms: [
      'data analysis',
      'analytics',
      'power bi',
      'tableau',
      'powerbi',
      'تحلیل داده',
      'داشبوردسازی',
      'dashboard',
    ],
    category: 'skill',
  },
  {
    canonical: 'erp_sap',
    forms: ['sap', 'sap erp', 'ساپ', 'erp', 'microsoft dynamics', 'dynamics 365', 'ای‌آر‌پی'],
    category: 'skill',
  },
  {
    canonical: 'jira_tool',
    forms: ['jira', 'confluence', 'جیرا', 'کانفلوئنس'],
    category: 'skill',
  },
  {
    canonical: 'networking',
    forms: [
      'tcp/ip',
      'dns',
      'dhcp',
      'vlan',
      'routing',
      'switching',
      'mikrotik',
      'cisco',
      'فایروال',
      'firewall',
      'سیسکو',
      'مایکروتیک',
    ],
    category: 'skill',
  },
  {
    canonical: 'iot',
    forms: ['iot', 'internet of things', 'اینترنت اشیا', 'embedded', 'سخت افزار', 'امبدد'],
    category: 'skill',
  },

  // ---- Locations ----------------------------------------------------------
  { canonical: 'tehran', forms: ['tehran', 'تهران'], category: 'location' },
  { canonical: 'isfahan', forms: ['isfahan', 'esfahan', 'اصفهان'], category: 'location' },
  { canonical: 'karaj', forms: ['karaj', 'کرج'], category: 'location' },
  { canonical: 'mashhad', forms: ['mashhad', 'مشهد'], category: 'location' },
  { canonical: 'shiraz', forms: ['shiraz', 'شیراز'], category: 'location' },
  { canonical: 'tabriz', forms: ['tabriz', 'تبریز'], category: 'location' },
  { canonical: 'ahvaz', forms: ['ahvaz', 'اهواز'], category: 'location' },
  { canonical: 'qom', forms: ['qom', 'ghom', 'قم'], category: 'location' },
  { canonical: 'rasht', forms: ['rasht', 'رشت'], category: 'location' },
  { canonical: 'kerman', forms: ['kerman', 'کرمان'], category: 'location' },
  { canonical: 'yazd', forms: ['yazd', 'یزد'], category: 'location' },
  {
    canonical: 'bandar_abbas',
    forms: ['bandar abbas', 'بندرعباس', 'بندر عباس'],
    category: 'location',
  },
  { canonical: 'qazvin', forms: ['qazvin', 'قزوین'], category: 'location' },
  {
    canonical: 'kermanshah',
    forms: ['kermanshah', 'کرمانشاه'],
    category: 'location',
  },
  { canonical: 'zahedan', forms: ['zahedan', 'زاهدان'], category: 'location' },
  { canonical: 'urmia', forms: ['urmia', 'orumieh', 'ارومیه'], category: 'location' },
  { canonical: 'kashan', forms: ['kashan', 'کاشان'], category: 'location' },
  {
    canonical: 'alborz',
    forms: ['alborz', 'alborz province', 'البرز', 'کرج'],
    category: 'location',
  },
  { canonical: 'gilan', forms: ['gilan', 'گیلان', 'رشت'], category: 'location' },
  {
    canonical: 'khuzestan',
    forms: ['khuzestan', 'خوزستان', 'اهواز'],
    category: 'location',
  },
  {
    canonical: 'eslamshahr',
    forms: ['eslamshahr', 'اسلامشهر'],
    category: 'location',
  },
  {
    canonical: 'remote',
    forms: [
      'remote',
      'remotely',
      'work from home',
      'wfh',
      'دورکاری',
      'دور کار',
      'از راه دور',
      'غیرحضوری',
      'دور از محل',
    ],
    category: 'location',
  },
  {
    canonical: 'hybrid',
    forms: ['hybrid', 'ترکیبی', 'نیمه حضوری', 'حضوری و دورکار', 'حضوری/دورکاری'],
    category: 'location',
  },

  // ---- Employment types ----------------------------------------------------
  {
    canonical: 'full_time',
    forms: ['full time', 'full-time', 'تمام وقت', 'تمام‌وقت', 'full-time employment'],
    category: 'employment_type',
  },
  {
    canonical: 'part_time',
    forms: ['part time', 'part-time', 'پاره وقت', 'پاره‌وقت', 'نیمه وقت'],
    category: 'employment_type',
  },
  {
    canonical: 'contract',
    forms: ['contract', 'contractor', 'قراردادی', 'پروژه ای', 'پروژه‌ای', 'project-based'],
    category: 'employment_type',
  },
  {
    canonical: 'internship',
    forms: ['internship', 'intern', 'کارآموزی', 'کارآموز'],
    category: 'employment_type',
  },
  {
    canonical: 'freelance',
    forms: ['freelance', 'freelancer', 'فریلنس', 'فریلنسر', 'پروژه‌محور آزاد'],
    category: 'employment_type',
  },
  {
    canonical: 'temporary',
    forms: ['temporary', 'temp', 'موقت', 'موقتی'],
    category: 'employment_type',
  },

  // ---- Remote policies -----------------------------------------------------
  {
    canonical: 'remote',
    forms: ['remote', 'remotely', 'دورکاری', 'از راه دور', 'غیرحضوری', 'تمام دورکاری'],
    category: 'remote_policy',
  },
  {
    canonical: 'onsite',
    forms: ['onsite', 'on-site', 'on site', 'حضوری', 'در محل شرکت', 'تمام حضوری'],
    category: 'remote_policy',
  },
  {
    canonical: 'hybrid',
    forms: ['hybrid', 'ترکیبی', 'نیمه‌حضوری', 'ترکیبی (حضوری و دورکاری)'],
    category: 'remote_policy',
  },

  // ---- Seniority -----------------------------------------------------------
  {
    canonical: 'junior',
    forms: ['junior', 'jr', 'jr.', 'جونیور', 'تازه‌کار', 'تازه کار', 'کم‌تجربه', 'کم تجربه'],
    category: 'seniority',
  },
  {
    canonical: 'mid_level',
    forms: ['mid-level', 'mid level', 'mid', 'میان‌رده', 'میان رده', 'میانه'],
    category: 'seniority',
  },
  {
    canonical: 'senior',
    forms: [
      'senior',
      'sr',
      'sr.',
      'سنیور',
      'ارشد',
      'کارشناس ارشد',
      'مهندس ارشد',
      'برنامه نویس ارشد',
      'برنامه‌نویس ارشد',
      'specialist',
    ],
    category: 'seniority',
  },
  {
    canonical: 'lead',
    forms: ['lead', 'team lead', 'تیم لید', 'سرپرست', 'رهبر تیم'],
    category: 'seniority',
  },
  {
    canonical: 'principal',
    forms: ['principal', 'staff engineer', 'staff', 'پرینسیپال', 'استف انجینر', 'بالاتر از ارشد'],
    category: 'seniority',
  },
  {
    canonical: 'manager',
    forms: ['manager', 'مدیر', 'director', 'مدیریت'],
    category: 'seniority',
  },
  {
    canonical: 'head',
    forms: ['head of', 'head', 'سرپرست کل', 'مدیر ارشد'],
    category: 'seniority',
  },

  // ---- Industries ----------------------------------------------------------
  {
    canonical: 'fintech',
    forms: ['fintech', 'فین تک', 'فین‌تک', 'فینتک', 'financial technology'],
    category: 'industry',
  },
  {
    canonical: 'ecommerce',
    forms: [
      'e-commerce',
      'ecommerce',
      'خرید اینترنتی',
      'فروشگاه اینترنتی',
      'فروشگاه آنلاین',
      'تجارت الکترونیک',
    ],
    category: 'industry',
  },
  {
    canonical: 'healthcare',
    forms: ['healthcare', 'health tech', 'سلامت دیجیتال', 'درمان', 'سلامت', 'پزشکی'],
    category: 'industry',
  },
  {
    canonical: 'gaming',
    forms: ['gaming', 'game', 'game development', 'بازی سازی', 'صنعت بازی', 'بازی‌سازی'],
    category: 'industry',
  },
  {
    canonical: 'saas',
    forms: ['saas', 'software as a service', 'ساس', 'نرم افزار به عنوان سرویس'],
    category: 'industry',
  },
  {
    canonical: 'telecom',
    forms: ['telecom', 'telecommunications', 'مخابرات', 'ارتباطات'],
    category: 'industry',
  },
  {
    canonical: 'insurance',
    forms: ['insurance', 'بیمه', 'بیمه‌گری'],
    category: 'industry',
  },
  {
    canonical: 'banking',
    forms: ['banking', 'bank', 'بانکداری', 'بانک', 'صرافی', 'exchange'],
    category: 'industry',
  },
  {
    canonical: 'logistics',
    forms: ['logistics', 'shipping', 'حمل و نقل', 'لجستیک', 'پست'],
    category: 'industry',
  },
  {
    canonical: 'automotive',
    forms: ['automotive', 'خودرو', 'صنعت خودرو', 'خودروسازی'],
    category: 'industry',
  },
  {
    canonical: 'energy',
    forms: ['energy', 'oil', 'gas', 'انرژی', 'نفت و گاز', 'پتروشیمی'],
    category: 'industry',
  },
  {
    canonical: 'retail',
    forms: ['retail', 'chain store', 'خرده فروشی', 'فروشگاه زنجیره ای', 'فروشگاه‌های زنجیره‌ای'],
    category: 'industry',
  },
  {
    canonical: 'education',
    forms: ['education', 'edtech', 'آموزش', 'فناوری آموزشی'],
    category: 'industry',
  },
  {
    canonical: 'tourism',
    forms: ['tourism', 'travel', 'گردشگری', 'مسافرتی', 'هتل'],
    category: 'industry',
  },
];
